# Generated by Django 4.0.5 on 2022-07-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='arte',
            name='estado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arte',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
