# Generated by Django 4.0.5 on 2022-07-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacto_arte_estado_arte_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='imagen',
            field=models.ImageField(null=True, upload_to='artes'),
        ),
    ]
