# Generated by Django 4.0.5 on 2022-07-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_arte_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='arte',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombredelarte'),
        ),
    ]
